#!/usr/bin/env node

const Fs = require('fs');
const Path = require('path');
const Jimp = require('jimp');

const sourceDir = process.argv[2];
const outputFile = process.argv[3] || Path.join(__dirname, '..', 'src', 'staticFiles', 'item-icons-embedded.js');
const iconSize = parseInt(process.argv[4] || '48', 10);

if (!sourceDir) {
    console.error('Usage: node scripts/generate_item_icons.js <Rust Bundles/items folder> [outputFile] [size]');
    console.error('Example: node scripts/generate_item_icons.js "C:\\SteamLibrary\\steamapps\\common\\Rust\\Bundles\\items"');
    process.exit(1);
}

if (!Number.isInteger(iconSize) || iconSize < 16 || iconSize > 128) {
    console.error('Icon size must be an integer between 16 and 128 pixels.');
    process.exit(1);
}

async function main() {
    const inputDir = Path.resolve(sourceDir);
    const outputPath = Path.resolve(outputFile);
    const files = Fs.readdirSync(inputDir);
    const jsonByBaseName = new Map();

    for (const file of files) {
        if (!file.toLowerCase().endsWith('.json')) continue;
        const fullPath = Path.join(inputDir, file);
        const item = JSON.parse(Fs.readFileSync(fullPath, 'utf8'));
        const baseName = Path.basename(file, '.json');
        jsonByBaseName.set(baseName, item);
    }

    const icons = {};
    let processed = 0;
    for (const file of files) {
        if (!file.toLowerCase().endsWith('.png')) continue;
        const baseName = Path.basename(file, '.png');
        const item = jsonByBaseName.get(baseName);
        if (!item || item.itemid === undefined || !item.shortname) continue;

        const image = await Jimp.read(Path.join(inputDir, file));
        image.contain(iconSize, iconSize, Jimp.HORIZONTAL_ALIGN_CENTER | Jimp.VERTICAL_ALIGN_MIDDLE);
        const dataUri = await image.getBase64Async(Jimp.MIME_PNG);
        icons[item.itemid.toString()] = dataUri;
        processed += 1;
    }

    Fs.mkdirSync(Path.dirname(outputPath), { recursive: true });
    Fs.writeFileSync(outputPath, `// Generated by scripts/generate_item_icons.js. Do not edit manually.\nmodule.exports = ${JSON.stringify(icons)};\n`);
    console.log(`Embedded ${processed} item icons at ${iconSize}x${iconSize} into ${outputPath}`);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
