#!/usr/bin/env python3
"""Generate embedded Rust item icon data URIs for RustPlusPlus.

Reads Rust game item metadata and PNG files from a Bundles/items directory, resizes
icons to a small square canvas, and writes a CommonJS module consumed by
src/structures/Items.js.
"""

from __future__ import annotations

import argparse
import base64
import io
import json
import sys
from pathlib import Path

DEFAULT_SIZE = 48
MIN_SIZE = 16
MAX_SIZE = 128
DEFAULT_OUTPUT = Path(__file__).resolve().parents[1] / "src" / "staticFiles" / "item-icons-embedded.js"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Resize Rust item PNGs and embed them into a JS item icon map.",
        epilog=(
            "Example: python scripts/generate_item_icons.py "
            '"C:\\SteamLibrary\\steamapps\\common\\Rust\\Bundles\\items"'
        ),
    )
    parser.add_argument("source_dir", help="Path to Rust's Bundles/items directory")
    parser.add_argument(
        "--output",
        "-o",
        default=str(DEFAULT_OUTPUT),
        help=f"Output JS file (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--size",
        "-s",
        type=int,
        default=DEFAULT_SIZE,
        help=f"Square icon size in pixels, {MIN_SIZE}-{MAX_SIZE} (default: {DEFAULT_SIZE})",
    )
    return parser.parse_args()


def load_pillow():
    try:
        from PIL import Image
    except ImportError:
        print(
            "Pillow is required to resize PNGs. Install it on the machine that has the Rust item files with:\n"
            "  python -m pip install pillow",
            file=sys.stderr,
        )
        raise SystemExit(1)
    return Image


def read_item_metadata(source_dir: Path) -> dict[str, dict]:
    metadata: dict[str, dict] = {}
    for json_path in source_dir.glob("*.json"):
        try:
            with json_path.open("r", encoding="utf-8-sig") as file:
                item = json.load(file)
            metadata[json_path.stem] = item
        except (OSError, json.JSONDecodeError) as err:
            print(f"Skipping {json_path.name}: {err}", file=sys.stderr)
    return metadata


def resize_png_to_data_uri(image_path: Path, size: int, image_module) -> str:
    with image_module.open(image_path) as image:
        image = image.convert("RGBA")
        image.thumbnail((size, size), image_module.Resampling.LANCZOS)
        canvas = image_module.new("RGBA", (size, size), (0, 0, 0, 0))
        x = (size - image.width) // 2
        y = (size - image.height) // 2
        canvas.alpha_composite(image, (x, y))

        output = io.BytesIO()
        canvas.save(output, format="PNG", optimize=True)
        encoded = base64.b64encode(output.getvalue()).decode("ascii")
        return f"data:image/png;base64,{encoded}"


def generate_icons(source_dir: Path, size: int) -> dict[str, str]:
    image_module = load_pillow()
    metadata = read_item_metadata(source_dir)
    icons: dict[str, str] = {}

    for png_path in sorted(source_dir.glob("*.png")):
        item = metadata.get(png_path.stem)
        if not item or item.get("itemid") is None:
            continue
        try:
            icons[str(item["itemid"])] = resize_png_to_data_uri(png_path, size, image_module)
        except Exception as err:  # noqa: BLE001 - report and continue with other icons.
            print(f"Skipping {png_path.name}: {err}", file=sys.stderr)

    return icons


def write_commonjs_icon_map(output_path: Path, icons: dict[str, str]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(icons, separators=(",", ":"), sort_keys=True)
    output_path.write_text(
        "// Generated by scripts/generate_item_icons.py. Do not edit manually.\n"
        f"module.exports = {body};\n",
        encoding="utf-8",
    )


def main() -> int:
    args = parse_args()
    source_dir = Path(args.source_dir).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()

    if not source_dir.is_dir():
        print(f"Source directory does not exist: {source_dir}", file=sys.stderr)
        return 1
    if args.size < MIN_SIZE or args.size > MAX_SIZE:
        print(f"--size must be between {MIN_SIZE} and {MAX_SIZE} pixels.", file=sys.stderr)
        return 1

    icons = generate_icons(source_dir, args.size)
    write_commonjs_icon_map(output_path, icons)
    print(f"Embedded {len(icons)} item icons at {args.size}x{args.size} into {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
